# Generated by Django 5.0.7 on 2026-03-09 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget_Track', '0003_alter_transaction_pay_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pay_cycle',
            field=models.CharField(choices=[('CYCLE_1', 'First Pay Cycle'), ('CYCLE_2', 'Second Pay Cycle'), ('OTHER', 'Other')], default='CYCLE_1', max_length=10),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_1_day', models.PositiveIntegerField(default=10)),
                ('cycle_2_day', models.PositiveIntegerField(default=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
