# Generated by Django 5.0.7 on 2026-03-09 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget_Track', '0004_alter_transaction_pay_cycle_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_day', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_day'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Budget_Track.paycycle'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
