# Generated by Django 5.0.7 on 2026-03-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget_Track', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
